version: '3.8'

services:
  db:
    build: ./sql
    container_name: db_c
    restart: unless-stopped
    volumes:
      - db_v:/app
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beer
    ports:
      - "3307:3306"

volumes:
  db_v: